site_name: The Best Nexus Letters - Documentation
site_description: Professional nexus letter service documentation hub
site_url: https://docs.TheBestNexusLetters.com
repo_url: https://github.com/4eckd/the-best-nexus-letters
repo_name: TheBestNexusLetters
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github

extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/4eckd/TheBestNexusLetters
    - icon: fontawesome/brands/discord
      link: https://discord.gg/your-discord
  version:
    provider: mike
    default: stable

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: username
      repo: the-best-nexus-letters
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: 
    - Overview: index.md
    - Quick Start: quickstart.md
    - Installation: installation.md
  - Getting Started:
    - Setup Guide: getting-started/SETUP.md
    - Environment Configuration: getting-started/env.md
    - Development Guide: getting-started/DEVELOPMENT.md
    - Contributing: getting-started/CONTRIBUTING.md
  - Architecture:
    - System Overview: architecture/overview.md
    - Database Schema: architecture/database-schema.md
    - API Design: architecture/api-design.md
    - Security: architecture/security.md
  - Development:
    - Component Library: development/component-library.md
    - Testing Guide: development/TESTING.md
    - Theming System: development/THEMING.md
    - Hooks & Utilities: development/hooks-utilities.md
  - Integrations:
    - Supabase Setup: integrations/supabase-setup.md
    - Discourse Integration: integrations/discourse-integration.md
    - Authentication: integrations/authentication.md
    - External Services: integrations/external-services.md
  - Deployment:
    - Overview: deployment/overview.md
    - CI/CD Pipeline: deployment/cicd.md
    - Environment Variables: deployment/environment-variables.md
    - Performance: deployment/performance.md
  - Operations:
    - Monitoring: operations/monitoring.md
    - Logging: operations/logging.md
    - Troubleshooting: operations/troubleshooting.md
    - Runbook: operations/runbook.md
  - API Reference:
    - Overview: api/overview.md
    - Authentication: api/auth.md
    - User Management: api/users.md
    - Letters: api/letters.md
  - Reference:
    - Environment Variables: reference/env-vars.md
    - CLI Commands: reference/cli.md
    - FAQ: reference/faq.md
    - Changelog: CHANGELOG.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2025 <a href="thebestnexusletters.com" target="_blank" rel="noopener">The Best Nexus Letters</a>
